Enum:
  ColorConversion:
    BGR2RGB: 4
    BGR2GRAY: 6
    RGB2GRAY: 7
    BGR2HSV: 40
  RotateAngle:
    '90' : 90
    '180' : 180
    '270': 270   

Type:
  cvImage:
    ctl: CvImage 


Config:
  Task:    
    ImRead:
      description:
      input:
      - name: filename 
        type: filepath
      output: 
      - name: default
        type: cvImage 
    ImWrite:
      description:
      input:
      - name: filename 
        type: filepath
      - name: img 
        type: cvImage
    CvtColor:
      description:
      input:
      - name: source 
        type: cvImage
      - name: code 
        type: Enum.ColorConversion
      output:
      - name: default 
        type: cvImage
    Canny:
      description: Canny edge detector
      input:
      - name: image 
        type: cvImage
      - name: threshold1 
        type: byte
      - name: threshold2 
        type: byte  
      output:
      - name: default 
        type: cvImage
    Rotate:
      description: "Rotates using multiple 90"
      input:
      - name: image 
        type: cvImage
      - name: angle 
        type: Enum.RotateAngle     
      output:
      - name: default 
        type: cvImage
    Resize:
      description: Resize image
      input:
      - name: image 
        type: cvImage
      - name: percent 
        type: decimal 
      output:
      - name: default 
        type: cvImage 
    Crop:
      description: Crop image
      input:
      - name: image 
        type: cvImage
      - name: rectangle 
        type: Rectangle
      output:
      - name: default 
        type: cvImage            


    



       



 


       
